// #if API==1.0
// /* global hmSetting */
export * from './sensors/_constants'
export { Accelerometer } from './sensors/accelerometer'
export { Barometer } from './sensors/barometer'
export { Battery } from './sensors/battery'
export { BloodOxygen } from './sensors/bloodOxygen'
export { Calorie } from './sensors/calorie'
export { Compass } from './sensors/compass'
export { Distance } from './sensors/distance'
export { FatBurning } from './sensors/fatBurning'
export { Geolocation } from './sensors/geolocation'
export { Gyroscope } from './sensors/gyroscope'
export { HeartRate } from './sensors/heartRate'
export { Pai } from './sensors/pai'
export { Screen } from './sensors/screen'
export { Sleep } from './sensors/sleep'
export { Stand } from './sensors/stand'
export { Step } from './sensors/step'
export { Stress } from './sensors/stress'
export { Time } from './sensors/time'
export { Vibrator } from './sensors/vibrator'
export { Wear } from './sensors/wear'
export { Weather } from './sensors/weather'
export { Workout } from './sensors/workout'
export { WorldClock } from './sensors/worldClock'
// #endif
